import type { Rayon } from "./types";
import { rayonEmoji } from "./shopping";

/**
 * Un emoji par ingrédient, pour donner un visuel à chaque ligne de la liste de
 * courses et du détail recette (là où une photo n'a pas sa place).
 *
 * Les clés sont les noms d'ingrédients tels qu'ils apparaissent dans
 * `data/recipes.json`, en minuscules. Un ingrédient inconnu retombe sur un
 * mot-clé (« poulet », « fromage »…) puis sur l'emoji de son rayon : la liste
 * n'a donc jamais de trou, même après l'ajout d'une recette.
 *
 * Choix volontairement limité aux emojis largement supportés (≤ Unicode 14),
 * pour éviter les tofus (le carré vide, pas l'ingrédient) sur les vieux mobiles.
 */
const EMOJI: Record<string, string> = {
  // ── Boucherie / Poisson ────────────────────────────────────────────────────
  "agneau haché": "🐑",
  anchois: "🐟",
  bacon: "🥓",
  "bœuf haché": "🥩",
  "bœuf à mijoter": "🥩",
  "bœuf à pot-au-feu": "🥩",
  "bœuf émincé": "🥩",
  "confit de canard effiloché": "🦆",
  "côte de porc": "🍖",
  crevettes: "🍤",
  "cuisse de poulet": "🍗",
  dorade: "🐟",
  "dos de cabillaud": "🐟",
  "escalope de poulet": "🍗",
  "filet de colin": "🐟",
  "filet de poisson blanc": "🐟",
  "filet de poulet": "🍗",
  jambon: "🍖",
  lardons: "🥓",
  "lardons fumés": "🥓",
  merguez: "🌭",
  moules: "🦪",
  "pavé de saumon": "🐟",
  sardines: "🐟",
  "saucisse de toulouse": "🌭",
  "saumon fumé": "🐟",
  "sauté de porc": "🍖",
  "sauté de veau": "🍖",
  "steak de thon": "🐟",
  "émincé de poulet": "🍗",

  // ── Fruits & Légumes ───────────────────────────────────────────────────────
  ail: "🧄",
  aneth: "🌿",
  aubergine: "🍆",
  avocat: "🥑",
  basilic: "🌿",
  brocoli: "🥦",
  carotte: "🥕",
  champignons: "🍄",
  "champignons de paris": "🍄",
  chou: "🥬",
  "chou chinois": "🥬",
  "chou rouge": "🥬",
  "chou-fleur": "🥦",
  citron: "🍋",
  "citron vert": "🍋",
  citronnelle: "🌿",
  concombre: "🥒",
  coriandre: "🌿",
  "courge butternut": "🎃",
  courgette: "🥒",
  céleri: "🥬",
  endives: "🥬",
  gingembre: "🌿",
  menthe: "🌿",
  navet: "🥔",
  oignon: "🧅",
  "oignon nouveau": "🧅",
  "oignon rouge": "🧅",
  "pak choï": "🥬",
  persil: "🌿",
  poireau: "🥬",
  poivron: "🫑",
  "pomme de terre": "🥔",
  "pommes de terre": "🥔",
  potiron: "🎃",
  roquette: "🥬",
  salade: "🥬",
  "salade romaine": "🥬",
  tomate: "🍅",
  "tomates cerises": "🍅",
  échalote: "🧅",
  épinards: "🥬",
  "épinards frais": "🥬",

  // ── Crèmerie ───────────────────────────────────────────────────────────────
  beurre: "🧈",
  béchamel: "🥛",
  "bûche de chèvre": "🐐",
  cheddar: "🧀",
  "chèvre frais": "🐐",
  "crème fraîche": "🥛",
  emmental: "🧀",
  feta: "🧀",
  "fromage râpé": "🧀",
  gorgonzola: "🧀",
  gruyère: "🧀",
  "gruyère râpé": "🧀",
  halloumi: "🧀",
  lait: "🥛",
  mozzarella: "🧀",
  parmesan: "🧀",
  "parmesan râpé": "🧀",
  ravioles: "🥟",
  "sauce blanche": "🥛",
  yaourt: "🥛",
  œuf: "🥚",

  // ── Épicerie salée ─────────────────────────────────────────────────────────
  bouillon: "🍲",
  "bouillon de légumes": "🍲",
  "bouillon de volaille": "🍲",
  boulgour: "🌾",
  chapelure: "🍞",
  coquillettes: "🍝",
  cumin: "🧂",
  curry: "🍛",
  câpres: "🫒",
  farine: "🌾",
  "feuilles de lasagne": "🍝",
  gnocchi: "🥔",
  "haricots noirs": "🫘",
  "haricots rouges": "🫘",
  "herbes de provence": "🌿",
  houmous: "🥣",
  huile: "🌻",
  "huile d'olive": "🫒",
  "huile de sésame": "🌾",
  ketchup: "🍅",
  kimchi: "🥬",
  "lait de coco": "🥥",
  "lentilles corail": "🫘",
  "lentilles vertes": "🫘",
  levure: "🍞",
  macaroni: "🍝",
  maïs: "🌽",
  maïzena: "🌽",
  moutarde: "🥫",
  muscade: "🌰",
  nouilles: "🍜",
  "nouilles chinoises": "🍜",
  "nouilles de riz": "🍜",
  "nouilles soba": "🍜",
  "olives noires": "🫒",
  orecchiette: "🍝",
  paprika: "🌶️",
  penne: "🍝",
  piment: "🌶️",
  "piment d'espelette": "🌶️",
  "piment séché": "🌶️",
  "pois chiches": "🫘",
  polenta: "🌽",
  quinoa: "🌾",
  rigatoni: "🍝",
  riz: "🍚",
  "riz arborio": "🍚",
  "riz basmati": "🍚",
  "sauce césar": "🥗",
  "sauce soja": "🥢",
  "sauce tomate": "🍅",
  sel: "🧂",
  semoule: "🌾",
  spaghetti: "🍝",
  sésame: "🌾",
  tagliatelles: "🍝",
  tahini: "🥣",
  "thon en boîte": "🥫",
  thym: "🌿",
  "tofu ferme": "🧊",
  "tomates concassées": "🥫",
  vermicelles: "🍜",
  "vin blanc": "🍷",
  "vin rouge": "🍷",
  vinaigrette: "🥗",
  "épices ras el hanout": "🧂",

  // ── Épicerie sucrée ────────────────────────────────────────────────────────
  "beurre de cacahuète": "🥜",
  cacahuètes: "🥜",
  "graines de courge": "🌻",
  miel: "🍯",
  noisettes: "🌰",
  noix: "🌰",
  "noix de cajou": "🥜",
  pignons: "🌰",
  "pignons de pin": "🌰",
  "sirop d'érable": "🍁",
  sucre: "🍬",

  // ── Surgelés ───────────────────────────────────────────────────────────────
  "cordon bleu": "🍗",
  falafels: "🧆",
  frites: "🍟",
  "petits pois": "🥬",

  // ── Boulangerie ────────────────────────────────────────────────────────────
  croûtons: "🍞",
  "galette de sarrasin": "🥞",
  pain: "🥖",
  "pain burger": "🍔",
  "pain de mie": "🍞",
  "pain pita": "🫓",
  "pâte brisée": "🥧",
  "pâte feuilletée": "🥐",
  "pâte à pizza": "🍕",
  tortilla: "🫓",
  tortillas: "🫓",
};

// Repli par mot-clé pour tout ingrédient absent de la table (nouvelle recette,
// variante d'orthographe…). L'ordre compte : le premier motif qui matche gagne.
const MOTS_CLES: [RegExp, string][] = [
  [/poulet|volaille|dinde/, "🍗"],
  [/bœuf|boeuf|steak|veau|agneau/, "🥩"],
  [/porc|jambon|lard|bacon/, "🥓"],
  [/saucisse|merguez|chorizo/, "🌭"],
  [/saumon|thon|cabillaud|colin|poisson|dorade|sardine|anchois/, "🐟"],
  [/crevette|gambas|moule|crustac/, "🍤"],
  [/fromage|parmesan|gruyère|emmental|cheddar|mozzarella|feta/, "🧀"],
  [/lait|crème|yaourt/, "🥛"],
  [/œuf|oeuf/, "🥚"],
  [/pâtes|penne|spaghetti|nouille|macaroni|lasagne|tagliatelle/, "🍝"],
  [/riz|risotto/, "🍚"],
  [/lentille|haricot|pois chiche|fève/, "🫘"],
  [/salade|épinard|chou|roquette|blette/, "🥬"],
  [/tomate/, "🍅"],
  [/pomme de terre|patate/, "🥔"],
  [/pain|brioche|baguette/, "🥖"],
  [/herbes?|persil|basilic|thym|menthe|coriandre|aneth/, "🌿"],
  [/épice|curry|paprika|cumin|sel|poivre/, "🧂"],
  [/huile/, "🫒"],
  [/sucre|miel|sirop/, "🍯"],
];

const norm = (nom: string) => nom.toLowerCase().trim();

/** Emoji d'un ingrédient : table exacte, puis mot-clé, puis emoji du rayon. */
export function ingredientEmoji(nom: string, rayon?: Rayon): string {
  const n = norm(nom);
  const exact = EMOJI[n];
  if (exact) return exact;
  for (const [motif, emoji] of MOTS_CLES) {
    if (motif.test(n)) return emoji;
  }
  return rayon ? rayonEmoji(rayon) : "🛒";
}
